### ISSUE TITLE
Trouble displaying equations with MathJax

### ISSUE THREAD

**Issue by tobydriscoll** [fongandrew/hydeout#11]
The theme is great and I appreciate the work behind it. I'm trying to use it for some math lecture notes, and I found a bug with how MathJax displays equations. Here's a screenshot of the problem:

![image](https://user-images.githubusercontent.com/3577518/34695876-83194582-f49a-11e7-810b-f9bf92c2a7cb.png)

I've attached a minimal site that produces the result. It just has an include for the MathJax script header and a single MD page that produces a few equations. Should be able to serve it and view test.html to see the problem:

[notes copy.zip](https://github.com/fongandrew/hydeout/files/1613309/notes.copy.zip)

I'm 95% confident it's a bad CSS interaction; the MXJc-display enclosing element has zero height, which is not what I see on other MathJax content I've generated. But I'm out of my depth trying to pinpoint the problem.

**Comment by bluemurder** [comment]
Hello, I added mathjax support to my hydeout site and rendering seems ok. I added the link 
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

You used:
```
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'></script>
```

You can try blindly to use a mathjax configuration similar to mine. But I'm not sure if it can really help

**Comment by tobydriscoll** [comment]
Thanks for trying. I found that by using mathjax-node as the kramdown engine, things look normal.
