### ISSUE TITLE
how to add image

### ISSUE THREAD

**Issue by erata** [fongandrew/hydeout#12]
hi, i try hydeout and add some images in but links broken. what is the right way to link to image.
i tried as [link text](/assets/file_name.jpg)

**Comment by fongandrew** [comment]
Hi, I'm not sure I understand your question.  The way you link should be similar to pretty much any other Jekyll theme.

An example:

```
[![Some title text]({{ site.url }}{{ site.baseurl }}/assets/path/to/img.jpg)]({{ site.url }}{{ site.baseurl }}/assets/path/to/img.jpg)
```

**Comment by JasonJunJun** [comment]
@fongandrew Isn't `![Some title text]({{ site.url }}{{ site.baseurl }}/assets/path/to/img.jpg)` enough to add an image?

**Comment by fongandrew** [comment]
Yes, the former is if you want to link the image to itself.
