### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by cesards** [fongandrew/hydeout#13]
I just wanted to reach the maintainers of this repository, because, after three years reading code of different Jekyll Theme contributions related to Jekyll, I think this is one of the most beautiful repositories I've seen so far. Very maintainable, clean and readable code. I always want to achieve code like this for my personal web projects, even being an Android Dev, I can appreciate this repo as a piece of art!

Thank you so much for a great job!

**Comment by fongandrew** [comment]
Thanks for the feedback! And you're welcome!
