### ISSUE TITLE
Sidebar order

### ISSUE THREAD

**Issue by arcanis** [fongandrew/hydeout#17]
Hey, nice theme!

Could it be possible to implement a way to configure the order the elements appear in the sidebar? They seem to be currently sorted by name, which might be impractical in some cases. Some `order` parameter in the Front Matter block would be enough.

**Comment by fongandrew** [comment]
It's not exactly alphabetical. The order is to display page links first, then category links, then things in a custom links includes. See https://github.com/fongandrew/hydeout/blob/master/_includes/sidebar-nav-links.html. Are you suggesting sorting within just page links or across all links? The former seems much more doable than the latter.

Anyhow, in the meantime, if you have a small number of things you want a custom sort order for, it's probably easier to just override that file manually,

**Comment by arcanis** [comment]
In my use case just pages would be fine. I'm currently sorting them by prefixing them with `01_`, ... but it's not great if I need to add one in the middle, and it messes with the urls: https://arcanis.github.io/prompto/

**Comment by fongandrew** [comment]
Sorry for the long turnaround time on this. You can specify a `sidebar_sort_order` in v3.7.0 now.
