### ISSUE TITLE
Google search did not match any documents 

### ISSUE THREAD

**Issue by miranda-zhang** [fongandrew/hydeout#23]
I tried the Google search on demo site, it always show
`Your search - xxxxxxx site:fongandrew.github.io/hydeout/hydeout - did not match any documents.`
Is this a bug or something won't work with demo?

**Comment by fongandrew** [comment]
Ah, this looks like a bug. There's an extra `/hydeout` after then`site:`. Thanks for reporting!

**Comment by fongandrew** [comment]
Fixed by #32. Thanks @j3soon!
