### ISSUE TITLE
Part of the format shows an error in IE11

### ISSUE THREAD

**Issue by RockyQu** [fongandrew/hydeout#26]

**Comment by fongandrew** [comment]
Don't know exactly what error you saw (please provide more details in the future), but just fixed an icon issue on IE11, so going to close this issue.

**Comment by RockyQu** [comment]
like this
![qq 20180611103302](https://user-images.githubusercontent.com/11417715/41210280-47e08088-6d63-11e8-8c3b-b6d9a6e09584.png)
