### ISSUE TITLE
Open Graph and Twitter Card integration?

### ISSUE THREAD

**Issue by twhite96** [fongandrew/hydeout#27]
I *love* this fork. Thanks for working on it.

I was wondering if you could incorporate Open Graph and Twitter Cards into the theme? If not, could you perhaps suggest some gems I could use?

Thanks!

**Comment by fongandrew** [comment]
Thanks! Sorry for the long response time. I don't have gems to personally recommend, but it seems like lots of people use https://github.com/jekyll/jekyll-seo-tag.

The [installation docs](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/installation.md) say you need to add an `{% seo %}` tag to the template. I recommend creating a file called `_includes/custom-head.html` with that tag. It should automatically add everything you need to the end of the `<head>` element on each page.

I'm going to close this issue, but feel free to follow up / reopen an issue if that doesn't work.
