### ISSUE TITLE
Hydeout doesn't show posts until I add pagination config

### ISSUE THREAD

**Issue by Morozzzko** [fongandrew/hydeout#29]
So, I tried to install the theme to a new Jekyll website, and couldn't see any of the posts

![no posts](https://user-images.githubusercontent.com/887264/40579363-6193b374-612e-11e8-9864-adaefff5b758.png)

How to reproduce:

* `jekyll new myblog`
* add `github-pages` and `jekyll-remote-theme` gems
* `bundle`
* add `remote_theme: fongandrew/hydeout` to `_config.yml` 
* run `jekyll serve`

Spent quite a lot of time to get things working. Turns out, my `_config.yml` was missing a line:

```
paginate: 5
```

Adding the config solves the problem:

![has posts](https://user-images.githubusercontent.com/887264/40579425-a3f6266a-612f-11e8-83a7-0a8751edfcb3.png)

Didn't see it anywhere in the docs, so I've created the issue

**Comment by fongandrew** [comment]
Thanks for pointing that out! I've added a small note to the README.
