### ISSUE TITLE
Github pages installation requires gemfile inclusion + _config.yml update

### ISSUE THREAD

**Issue by MSWorkers4Good** [fongandrew/hydeout#39]
To successfully install this theme with Github pages, I needed to not only add 

`gem "jekyll-theme-hydeout", "~> 3.4"` to `Gemfile`, but also needed to add

'remote_theme: fongandrew/hydeout' to the `_config.yml`. 

Just adding `gem 'github-pages', group: :jekyll_plugins` to the Gemfile didn't do it. Also, only having the 'remote_theme' specification in `_config.yml` didn't do it either.

This might be obvious to more experienced Jekyll users; I know that it would have saved me a lot of time to have had that note there.

**Comment by fongandrew** [comment]
Thanks. I made a small note in the README.
