### ISSUE TITLE
How can I adjust the page width?

### ISSUE THREAD

**Issue by LeeJunHyun** [fongandrew/hydeout#47]
How can I adjust the article width?

When I use wide-monitor, I feel the content width is too small.

I fail to find the proper variables at _variables.scss

thank you.

**Comment by cobbr** [comment]
I ran into a similar issue and found that editing the `max-width` value at line 211 of `_sass/hideout/_layout.scss` did the trick.

**Comment by LeeJunHyun** [comment]
@cobbr It works for me too!!! Thanks!!

**Comment by fongandrew** [comment]
Sorry for not responding sooner, but glad this was resolved.
