### ISSUE TITLE
Github Pages metadata clashes with config file

### ISSUE THREAD

**Issue by theholy7** [fongandrew/hydeout#48]
Having:

```yml
github:
    repo: "<repo_url>"
```
in the `_config.yml` file prevents the page from building successfully.

Also the theme is not correctly using (or doesn't allow the user to select) the [Github Pages Metadata](https://help.github.com/articles/repository-metadata-on-github-pages/).

For example, in the sidebar HTML file, we have `site.github.repo` rather than `site.github.repository_url`.

**Comment by holgerdell** [comment]
I can confirm the first issue. If site.github.repo is set in _config.yml, then github-pages (using the remote_theme functionality) refuses to build the site and gives the following error message:
> Your site is having problems building: The hydeout theme is not currently supported on GitHub Pages

**Comment by fongandrew** [comment]
This should be fixed in master and v4.0.0 of the gem. The `github` config in master is gone, and the `_config` in the `gh-pages` branch now uses a `hydeout.repo` instead.
