### ISSUE TITLE
After clicking the page (next page), HTTPS will become http. Why?

### ISSUE THREAD

**Issue by RockyQu** [fongandrew/hydeout#49]

**Comment by RockyQu** [comment]
It turns out that only on Chrome, HTTPS is redirected to http, which may be Chrome's problem. I'll try setting up Chrome to see if it works.

**Comment by RockyQu** [comment]
Maybe it's not your blog.

**Comment by fongandrew** [comment]
Closing since I can't reproduce. Feel free to open a new issue if you have a repro.
