### ISSUE TITLE
category-list like tags-list

### ISSUE THREAD

**Issue by yanxiwu** [fongandrew/hydeout#54]
Hello, 

Is it possible to have a similar, dynamic index filter for categories as the for tags?

https://fongandrew.github.io/hydeout/tags

Thanks! k

**Comment by fongandrew** [comment]
Probably! Although that's somewhat out of the scope of this theme. If you'd like to add it yourself though, create your own layout using this partial as starting point: https://github.com/fongandrew/hydeout/blob/7b67d485ef09981304c8096d946d94468f5fb79c/_includes/tags-list.html

Just change the instances of `site.tags` to `site.categories` and things should mostly work.
