### ISSUE TITLE
Github Pages - Theme not appearing

### ISSUE THREAD

**Issue by JanxSpirit42** [fongandrew/hydeout#57]
https://janxspirit42.github.io/

The site is just generating in plain text, I have taken a look at the other issues and added lines to Gemfile and _config.yml to no avail. Any ideas?

https://github.com/JanxSpirit42/janxspirit42.github.io

edit: typo

**Comment by krzjoa** [comment]
I have the same problem :(

**Comment by fongandrew** [comment]
In your config (https://github.com/JanxSpirit42/janxspirit42.github.io/blob/master/_config.yml), the `baseurl` is set to `'/blog'` but I'm guessing your site is hosted at https://janxspirit42.github.io (no `/blog`). Try changing the baseurl to just `''` or `'/'`.

**Comment by JanxSpirit42** [comment]
That worked! Not sure why \blog worked locally. Thank you for your help and thank you for making a great theme!
