### ISSUE TITLE
Not able to see my post at all 

### ISSUE THREAD

**Issue by pchaturv** [fongandrew/hydeout#58]
What I need to do so that post under _post folder appear on the Home page? I also tried locally but couldn't get it working.
Here is the link: https://pchaturv.github.io/Praveen/

I would highly appreciate any response.
Thanks

**Comment by fongandrew** [comment]
It looks like the posts are visible here (https://pchaturv.github.io/blog/). Hey commenting out the `sidebar_blog_link` in your `_config.yml` or setting it to `/Praveen`

**Comment by pchaturv** [comment]
great...thanks
