### ISSUE TITLE
Archive Page using jekyll-archives?

### ISSUE THREAD

**Issue by twhite96** [fongandrew/hydeout#59]
Trying to work with the [jekyll-archives](https://github.com/jekyll/jekyll-archives) gem and trying to build a layout. It isn't working currently: nothing is displayed in the archive page. I haven't pushed this to my repo.

My current archive page layout is;

```html
---
layout: default
---
<!DOCTYPE html>
<html lang="en">
<body>
  <header>
    <h1 class="page-title">{{ page.title }}</h1>
  </header>
  <div class="content">
    <h1>Archive of posts from {{ page.date | date: "%Y" }}</h1>

    <ul class="posts-lists">
    {% for post in page.posts %}
      <li>
        <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>
        <a class="post" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>
      </li>
    {% endfor %}
    </ul>
  </div>
</html>
```

The page in dev:

<img width="2558" alt="screenshot-2018-10-10_05-24-44_pm" src="https://user-images.githubusercontent.com/7698292/46766936-76404000-ccb1-11e8-9800-f53fc857c3e7.png">

Can you help me out or implement this is some way into Hydeout?

**Comment by fongandrew** [comment]
I'm not very familiar with how `jekyll-archives` works unfortunately. But a couple of things come to mind:

* Are you sure that layout needs a front matter? The `default` layout used by Hydeout already inserts a doctype + the HTML tags and everything else for you. Adding those things to a layout that extends `default` seems odd to me.

* Is anything missing from your `_config.yml`? Sharing that could be helpful.

**Comment by eifinger** [comment]
@fongandrew Do you have another idea on how to implement an Archive?

**Comment by twhite96** [comment]
I figured out how to get this to work. I created an archive page which you can find [here](https://github.com/twhite96/TWBlog/blob/master/archive.md) that accomplishes what I need. @eifinger maybe this will work for you. In the meantime, I am going to close this.
