### ISSUE TITLE
Scrollbar location in reverse-layout

### ISSUE THREAD

**Issue by tintin42** [fongandrew/hydeout#65]
I have been using Hyde for a few years and really like it, so was very happy to see that someone has taken up the theme! I do have some problems with it though and one is related to the reverse-layout. When I am using that in hydeout the scrollbar is located between the sidebar and the main section. In original Hyde the scroll bar is located all the way to the right, which looks much tidier. Or am I missing a customization option somewhere?

**Comment by fongandrew** [comment]
Sorry for the long response time but this is due to the same underlying issue as in #66. Going to close this issue out and leave that one open for now.
