### ISSUE TITLE
site.baseurl does not work correctly

### ISSUE THREAD

**Issue by JasonJunJun** [fongandrew/hydeout#68]
I have commented out `baseurl` in  [_config.yml](https://github.com/JasonJunJun/JasonJunJun.github.io/blob/master/_config.yml), but when I click `site.baseurl` in [404.html](https://jasonjunjun.github.io/404.html), the browser doesn't navigate to the `baseurl`, instead of [the current location](https://jasonjunjun.github.io/404.html).

**Comment by soldefierro** [comment]
I am having the same issue and have with multiple jekyll themes

**Comment by philipgriffin** [comment]
I've seen this too, for the time being, I have modified `404.html ` to specify the absolute base `<a href="/">Head back home</a>`.

**Comment by fongandrew** [comment]
Should be fixed now thanks to @Ditti4.
