### ISSUE TITLE
How to - Post truncation

### ISSUE THREAD

**Issue by robwolff3** [fongandrew/hydeout#69]
Let me start out by saying thank you so much for taking in this project and maintaining it! It was a huge bummer when I tired the original Hyde and it didn't work. Glad I found this project :smiley:

I noticed in the demo site when a post was very long it still put the entire thing in the home page even though it was limited to 5 posts. I think it would be great if posts truncated after a certain length and had a **Read More...** button when displayed in the home page. Keeping the home page at a reasonable length and drawing people into the post page where they can comment, etc,

Thoughts?

**Comment by philipgriffin** [comment]
If I'm understanding you correctly, I think the current implementation is better as it allows you to explicitly define where you want to break the post up with a read more section. 

If you are unaware of this feature below is an example of the usage:
```
---
layout: post
title: Hello Hydeout
excerpt_separator:  <!--more-->
--- 
```

Then just place `<!--more-->` where ever you want to truncate the post.

**Comment by robwolff3** [comment]
Huh, I totally missed that. That defiantly solves my problem. Thank you so much @philipgriffin !
