### ISSUE TITLE
Is there a way to change the syntax highlighting theme

### ISSUE THREAD

**Issue by bbatsov** [fongandrew/hydeout#76]
I find the default colours hard to read, but I'm not sure if there's an easy way to switch to some other syntax highlighting theme.

**Comment by fongandrew** [comment]
Sorry for the long response time. You just need to include an extra style sheet for a Rouge / Pygment theme. This repo over here has a bunch: https://github.com/jwarby/jekyll-pygments-themes

**Comment by bbatsov** [comment]
Thanks!
