### ISSUE TITLE
No CSS loaded for GitHub pages.

### ISSUE THREAD

**Issue by smabie** [fongandrew/hydeout#82]
Hi. I cloned the repo and pushed it to Github Pages. But it seems the CSS isn't loading. Here's the site: smabie.github.io 

Is there something I must do after I clone and push? Thanks!

**Comment by pveber** [comment]
Same problem here! @smabie it seems you solved the issue, would you have any hint?

**Comment by checkso** [comment]
same problem for me. did you fix it @pveber

**Comment by pveber** [comment]
no, sorry!

**Comment by ptaranat** [comment]
In `_config.yml`, instead of `theme:` use `remote_theme: fongandrew/hydeout`

**Comment by pveber** [comment]
thanks @ptaranat!

**Comment by xudong-yang** [comment]
Check your request record in the developer tool of the browser. If your `main.css` request is sent to `https://yourhostname/hydeout/assets/css/main.css`, but you put everything in the root folder, you need to change the `baseurl` from `"hydeout"` to `""`.

**Comment by shiami** [comment]
Change this:
`baseurl:          '/'`

**Comment by smabie** [comment]
Thanks guys, ended up fixing the problem awhile ago!
